import { PlantConfig, PlantPreset } from '../types/plant';

export const BASE_DEFAULT_CONFIG: PlantConfig = {
  id: 'default-plant',
  name: 'Default Botanical Symbol',
  description: 'Baseline recursive fractal tree symbol',
  seed: 42,
  maxDepth: 5,
  baseAngle: 35,
  angleJitter: 0.4,
  lengthRatio: 0.72,
  taperRatio: 0.75,
  trunkLength: 140,
  trunkThickness: 16,
  gravity: 0,
  splitsPerNode: 2,
  foliageType: 'deciduous',
  foliageDensity: 50,
  foliageSize: 10,
  foliageOpacity: 0.8,
  colorPalette: 'emerald',
  lineWeight: 1.5,
  style: 'vector',
  showDimensions: true,
  showGrid: true,
};

export const PLANT_PRESETS: PlantPreset[] = [
  {
    id: 'japanese_maple',
    name: 'Japanese Maple (Acer palmatum)',
    category: 'Trees',
    config: {
      seed: 12345,
      maxDepth: 5,
      baseAngle: 50,
      angleJitter: 0.6,
      lengthRatio: 0.75,
      taperRatio: 0.7,
      trunkLength: 110,
      trunkThickness: 18,
      gravity: -0.4, // Delicate horizontal drooping
      splitsPerNode: 3,
      foliageType: 'broadleaf',
      foliageDensity: 65,
      foliageSize: 9,
      colorPalette: 'maple_red',
    },
  },
  {
    id: 'italian_cypress',
    name: 'Italian Cypress (Cupressus sempervirens)',
    category: 'Trees',
    config: {
      seed: 98765,
      maxDepth: 6,
      baseAngle: 18, // Narrow upward branching
      angleJitter: 0.2,
      lengthRatio: 0.82,
      taperRatio: 0.8,
      trunkLength: 190,
      trunkThickness: 14,
      gravity: 0.8, // Strict upright orientation
      splitsPerNode: 2,
      foliageType: 'conifer',
      foliageDensity: 80,
      foliageSize: 7,
      colorPalette: 'pine_dark',
    },
  },
  {
    id: 'weeping_willow',
    name: 'Weeping Willow (Salix babylonica)',
    category: 'Trees',
    config: {
      seed: 55512,
      maxDepth: 6,
      baseAngle: 45,
      angleJitter: 0.5,
      lengthRatio: 0.78,
      taperRatio: 0.72,
      trunkLength: 130,
      trunkThickness: 22,
      gravity: -0.9, // Strong weeping droop
      splitsPerNode: 2,
      foliageType: 'weeping',
      foliageDensity: 70,
      foliageSize: 12,
      colorPalette: 'emerald',
    },
  },
  {
    id: 'scots_pine',
    name: 'Scots Pine (Pinus sylvestris)',
    category: 'Trees',
    config: {
      seed: 31415,
      maxDepth: 5,
      baseAngle: 40,
      angleJitter: 0.7,
      lengthRatio: 0.7,
      taperRatio: 0.78,
      trunkLength: 160,
      trunkThickness: 24,
      gravity: 0.1,
      splitsPerNode: 2,
      foliageType: 'conifer',
      foliageDensity: 55,
      foliageSize: 11,
      colorPalette: 'pine_dark',
    },
  },
  {
    id: 'architectural_elevation',
    name: 'Architectural Elevation Silhouette',
    category: 'Architectural Elevation',
    config: {
      seed: 77777,
      maxDepth: 5,
      baseAngle: 35,
      angleJitter: 0.3,
      lengthRatio: 0.72,
      taperRatio: 0.75,
      trunkLength: 140,
      trunkThickness: 16,
      gravity: 0,
      splitsPerNode: 2,
      foliageType: 'architectural_circle',
      foliageDensity: 45,
      foliageSize: 14,
      colorPalette: 'architectural_monochrome',
    },
  },
  {
    id: 'zen_bonsai',
    name: 'Zen Bonsai (Juniperus procumbens)',
    category: 'Shrubs & Bonsai',
    config: {
      seed: 44432,
      maxDepth: 5,
      baseAngle: 55,
      angleJitter: 0.8,
      lengthRatio: 0.68,
      taperRatio: 0.65,
      trunkLength: 90,
      trunkThickness: 26,
      gravity: -0.3,
      splitsPerNode: 2,
      foliageType: 'hatch',
      foliageDensity: 60,
      foliageSize: 6,
      colorPalette: 'bonsai_mint',
    },
  },
];
