import { PlantConfig, PlantPreset } from '../types/plant';

export const BASE_DEFAULT_CONFIG: PlantConfig = {
  id: 'default-plant',
  name: 'Japanese Maple',
  description: 'Decurrent canopy broadleaf tree symbol',
  seed: 42,
  growthProfile: 'decurrent_canopy',
  maxDepth: 5,
  baseAngle: 35,
  angleJitter: 0.4,
  lengthRatio: 0.72,
  taperRatio: 0.75,
  trunkLength: 140,
  trunkThickness: 16,
  gravity: 0,
  splitsPerNode: 2,

  // Radial Rosette
  rosetteLeafCount: 36,
  rosetteLeafLength: 140,
  rosetteCurl: 0.2,
  rosetteLayers: 3,

  // Columnar Spire
  spireWidth: 70,
  spireBranchAngle: 78,

  // Basal Fountain
  fountainBladeCount: 70,
  fountainArchFactor: 0.8,
  fountainBladeLength: 150,
  fountainSeedHeadDensity: 40,

  foliageType: 'deciduous',
  foliageDensity: 50,
  foliageSize: 10,
  foliageOpacity: 0.8,
  colorPalette: 'emerald',
  lineWeight: 1.5,
  style: 'vector',
  showDimensions: true,
  showGrid: true,
};

export const PLANT_PRESETS: PlantPreset[] = [
  {
    id: 'agave_rosette',
    name: 'Agave Americana (Radial Rosette)',
    category: 'Rosette & Succulents',
    config: {
      growthProfile: 'radial_rosette',
      seed: 12345,
      rosetteLeafCount: 42,
      rosetteLeafLength: 160,
      rosetteCurl: 0.35,
      rosetteLayers: 4,
      colorPalette: 'emerald',
      foliageType: 'broadleaf',
    },
  },
  {
    id: 'scots_pine_tower',
    name: 'Scots Pine (Excurrent Tower)',
    category: 'Conifers',
    config: {
      growthProfile: 'excurrent_tower',
      seed: 31415,
      trunkLength: 170,
      spireWidth: 160,
      baseAngle: 25,
      maxDepth: 5,
      foliageType: 'conifer',
      foliageDensity: 75,
      colorPalette: 'pine_dark',
    },
  },
  {
    id: 'japanese_maple_canopy',
    name: 'Japanese Maple (Decurrent Canopy)',
    category: 'Deciduous Trees',
    config: {
      growthProfile: 'decurrent_canopy',
      seed: 55512,
      maxDepth: 5,
      baseAngle: 48,
      angleJitter: 0.5,
      lengthRatio: 0.75,
      taperRatio: 0.7,
      trunkLength: 120,
      trunkThickness: 18,
      gravity: -0.4,
      splitsPerNode: 3,
      foliageType: 'broadleaf',
      foliageDensity: 65,
      colorPalette: 'maple_red',
    },
  },
  {
    id: 'italian_cypress_spire',
    name: 'Italian Cypress (Columnar Spire)',
    category: 'Spires',
    config: {
      growthProfile: 'columnar_spire',
      seed: 98765,
      trunkLength: 200,
      spireWidth: 55,
      spireBranchAngle: 82,
      maxDepth: 6,
      foliageType: 'conifer',
      foliageDensity: 85,
      colorPalette: 'pine_dark',
    },
  },
  {
    id: 'fountain_grass_basal',
    name: 'Ornamental Fountain Grass (Basal Fountain)',
    category: 'Grasses & Ferns',
    config: {
      growthProfile: 'basal_fountain',
      seed: 77712,
      fountainBladeCount: 85,
      fountainBladeLength: 160,
      fountainArchFactor: 1.1,
      fountainSeedHeadDensity: 50,
      colorPalette: 'autumn_gold',
    },
  },
];
