import { PlantConfig, PlantPreset } from '../types/plant';

export const BASE_DEFAULT_CONFIG: PlantConfig = {
  id: 'default-plant',
  name: 'Japanese Maple (Acer palmatum)',
  description: 'Decurrent canopy broadleaf tree symbol with organic Bezier branching',
  seed: 42,
  growthProfile: 'decurrent_canopy',
  renderTechnique: 'botanical_vector',
  
  // Organic Trunk Morphology
  trunkLength: 130,
  trunkThickness: 20,
  rootFlare: 0.9,
  barkFissures: 0.7,
  windDrift: 0.1,
  asymmetry: 0.4,

  // Branching Math
  maxDepth: 5,
  baseAngle: 45,
  angleJitter: 0.5,
  lengthRatio: 0.74,
  taperRatio: 0.72,
  gravity: -0.35,
  splitsPerNode: 2,

  // Radial Rosette
  rosetteLeafCount: 38,
  rosetteLeafLength: 150,
  rosetteCurl: 0.25,
  rosetteLayers: 4,

  // Columnar Spire
  spireWidth: 65,
  spireBranchAngle: 80,

  // Basal Fountain
  fountainBladeCount: 75,
  fountainArchFactor: 0.85,
  fountainBladeLength: 160,
  fountainSeedHeadDensity: 45,

  // Foliage & Blossoms
  foliageType: 'broadleaf',
  foliageDensity: 65,
  foliageSize: 11,
  foliageOpacity: 0.88,
  blossomDensity: 0,
  blossomColor: '#f472b6',
  colorPalette: 'maple_red',
  lineWeight: 1.3,
  showDimensions: true,
  showGrid: true,
};

export const PLANT_PRESETS: PlantPreset[] = [
  {
    id: 'japanese_maple_canopy',
    name: 'Japanese Maple (Decurrent Canopy)',
    category: 'Deciduous Trees',
    config: {
      growthProfile: 'decurrent_canopy',
      renderTechnique: 'botanical_vector',
      seed: 55512,
      maxDepth: 5,
      baseAngle: 48,
      angleJitter: 0.55,
      lengthRatio: 0.75,
      taperRatio: 0.7,
      trunkLength: 125,
      trunkThickness: 22,
      rootFlare: 1.0,
      barkFissures: 0.8,
      gravity: -0.4,
      splitsPerNode: 3,
      foliageType: 'broadleaf',
      foliageDensity: 70,
      foliageSize: 11,
      colorPalette: 'maple_red',
    },
  },
  {
    id: 'sakura_cherry_blossom',
    name: 'Sakura Flowering Cherry (Bonsai / Decurrent)',
    category: 'Deciduous Trees',
    config: {
      growthProfile: 'decurrent_canopy',
      renderTechnique: 'watercolor_wash',
      seed: 88821,
      maxDepth: 5,
      baseAngle: 52,
      angleJitter: 0.6,
      lengthRatio: 0.72,
      taperRatio: 0.68,
      trunkLength: 110,
      trunkThickness: 24,
      rootFlare: 1.2,
      barkFissures: 0.9,
      gravity: -0.25,
      splitsPerNode: 2,
      foliageType: 'blossom',
      foliageDensity: 50,
      blossomDensity: 85,
      blossomColor: '#fbcfe8',
      colorPalette: 'cherry_blossom',
    },
  },
  {
    id: 'scots_pine_tower',
    name: 'Scots Pine (Excurrent Tower)',
    category: 'Conifers',
    config: {
      growthProfile: 'excurrent_tower',
      renderTechnique: 'botanical_vector',
      seed: 31415,
      trunkLength: 180,
      trunkThickness: 26,
      rootFlare: 0.9,
      barkFissures: 0.85,
      spireWidth: 170,
      baseAngle: 28,
      maxDepth: 5,
      foliageType: 'conifer',
      foliageDensity: 80,
      foliageSize: 10,
      colorPalette: 'pine_dark',
    },
  },
  {
    id: 'italian_cypress_spire',
    name: 'Italian Cypress (Columnar Spire)',
    category: 'Spires',
    config: {
      growthProfile: 'columnar_spire',
      renderTechnique: 'architectural_ink',
      seed: 98765,
      trunkLength: 210,
      trunkThickness: 16,
      rootFlare: 0.6,
      barkFissures: 0.5,
      spireWidth: 58,
      spireBranchAngle: 82,
      maxDepth: 6,
      foliageType: 'conifer',
      foliageDensity: 88,
      colorPalette: 'pine_dark',
    },
  },
  {
    id: 'agave_rosette',
    name: 'Agave Americana (Radial Rosette)',
    category: 'Rosette & Succulents',
    config: {
      growthProfile: 'radial_rosette',
      renderTechnique: 'botanical_vector',
      seed: 12345,
      rosetteLeafCount: 44,
      rosetteLeafLength: 165,
      rosetteCurl: 0.35,
      rosetteLayers: 4,
      colorPalette: 'emerald',
      foliageType: 'broadleaf',
    },
  },
  {
    id: 'fountain_grass_basal',
    name: 'Ornamental Fountain Grass (Basal Fountain)',
    category: 'Grasses & Palms',
    config: {
      growthProfile: 'basal_fountain',
      renderTechnique: 'botanical_vector',
      seed: 77712,
      fountainBladeCount: 90,
      fountainBladeLength: 165,
      fountainArchFactor: 1.15,
      fountainSeedHeadDensity: 55,
      windDrift: 0.2,
      colorPalette: 'autumn_gold',
    },
  },
  {
    id: 'canary_date_palm',
    name: 'Canary Island Date Palm (Basal Fountain / Palm)',
    category: 'Grasses & Palms',
    config: {
      growthProfile: 'basal_fountain',
      renderTechnique: 'botanical_vector',
      seed: 99123,
      fountainBladeCount: 45,
      fountainBladeLength: 190,
      fountainArchFactor: 0.9,
      fountainSeedHeadDensity: 0,
      foliageType: 'palm',
      colorPalette: 'emerald',
    },
  },
  {
    id: 'architectural_oak_elevation',
    name: 'Architectural Elevation Oak (Ink & Stipple)',
    category: 'Deciduous Trees',
    config: {
      growthProfile: 'decurrent_canopy',
      renderTechnique: 'architectural_ink',
      seed: 66554,
      maxDepth: 5,
      baseAngle: 42,
      angleJitter: 0.4,
      lengthRatio: 0.74,
      taperRatio: 0.74,
      trunkLength: 145,
      trunkThickness: 28,
      rootFlare: 1.1,
      barkFissures: 0.9,
      foliageType: 'architectural_circle',
      foliageDensity: 55,
      colorPalette: 'architectural_monochrome',
    },
  },
];
