'use client';

import React, { useState } from 'react';
import { Copy, Check, Download, Code, FileCode } from 'lucide-react';
import { PlantConfig } from '@/lib/types/plant';
import { generatePlantGeometry } from '@/lib/engine/fractalPlant';

interface CodeViewerProps {
  plantConfig: PlantConfig;
  viewMode: 'front' | 'side' | 'plan';
}

export const CodeViewer: React.FC<CodeViewerProps> = ({ plantConfig, viewMode }) => {
  const [copied, setCopied] = useState(false);
  const [codeType, setCodeType] = useState<'script' | 'svg'>('script');

  const result = generatePlantGeometry(plantConfig, viewMode);

  // Generate clean TypeScript procedural script snippet representing this scripted plant
  const scriptSnippet = `/**
 * Bloom Scripted Plant - Procedural Botanical Generator
 * Config Seed: #${plantConfig.seed} | Species: ${plantConfig.name || 'Custom Botanical Symbol'}
 * View: ${viewMode.toUpperCase()} | Generated by Bloom CAD Engine
 */

export const scriptedPlantConfig = ${JSON.stringify(plantConfig, null, 2)};

export function renderPlantSVG(canvasWidth = 800, canvasHeight = 800) {
  // Pure recursive fractal math execution
  const maxDepth = ${plantConfig.maxDepth};
  const baseAngle = ${plantConfig.baseAngle}; // degrees
  const lengthRatio = ${plantConfig.lengthRatio};
  const taperRatio = ${plantConfig.taperRatio};
  const trunkLength = ${plantConfig.trunkLength};
  const trunkThickness = ${plantConfig.trunkThickness};
  const gravity = ${plantConfig.gravity};
  const foliageType = "${plantConfig.foliageType}";

  // Generates clean layered SVG vector element
  return \`${result.svgContent.replace(/`/g, '\\`')}\`;
}
`;

  const codeToShow = codeType === 'script' ? scriptSnippet : result.svgContent;

  const handleCopy = () => {
    navigator.clipboard.writeText(codeToShow);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const ext = codeType === 'script' ? 'ts' : 'svg';
    const blob = new Blob([codeToShow], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `plant-symbol-${plantConfig.seed}-${viewMode}.${ext}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex flex-col h-full bg-[#090d16] text-slate-200 overflow-hidden font-mono text-xs select-none">
      {/* Code Header Bar */}
      <div className="h-10 bg-[var(--bg-surface)] border-b border-[var(--border-color)] px-4 flex items-center justify-between shrink-0">
        <div className="flex items-center space-x-2">
          <FileCode className="w-4 h-4 text-emerald-400" />
          <span className="font-semibold text-[var(--text-primary)]">
            Scripted Plant Code Snippet
          </span>
          <span className="text-[10px] bg-emerald-500/10 text-emerald-400 px-2 py-0.5 rounded border border-emerald-500/20">
            TypeScript / Procedural SVG
          </span>
        </div>

        <div className="flex items-center space-x-2">
          {/* Code Format Switcher */}
          <div className="flex bg-[var(--bg-card)] border border-[var(--border-color)] rounded p-0.5 text-[11px]">
            <button
              onClick={() => setCodeType('script')}
              className={`px-2 py-0.5 rounded transition-all ${
                codeType === 'script' ? 'bg-emerald-600 text-white' : 'text-slate-400 hover:text-white'
              }`}
            >
              TS Script
            </button>
            <button
              onClick={() => setCodeType('svg')}
              className={`px-2 py-0.5 rounded transition-all ${
                codeType === 'svg' ? 'bg-emerald-600 text-white' : 'text-slate-400 hover:text-white'
              }`}
            >
              Raw SVG XML
            </button>
          </div>

          <button
            onClick={handleCopy}
            className="px-2.5 py-1 rounded bg-[var(--bg-card)] hover:bg-slate-700 text-slate-300 border border-[var(--border-color)] flex items-center space-x-1 transition-colors"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied!' : 'Copy Code'}</span>
          </button>

          <button
            onClick={handleDownload}
            className="px-2.5 py-1 rounded bg-emerald-600 hover:bg-emerald-500 text-white flex items-center space-x-1 transition-colors shadow"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download .{codeType === 'script' ? 'ts' : 'svg'}</span>
          </button>
        </div>
      </div>

      {/* Code Text Area */}
      <div className="flex-1 p-4 overflow-auto bg-[#070a10]">
        <pre className="text-[11px] leading-relaxed text-emerald-300/90 selection:bg-emerald-600 selection:text-white">
          <code>{codeToShow}</code>
        </pre>
      </div>
    </div>
  );
};
